config/routes.rb
Rails.application.routes.draw do
  resources :images
  resources :point_of_sales
  resources :clients
  get 'welcome/index'

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :point_of_sales
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :point_of_sale
end

app/models/point_of_sale.rb
class PointOfSale < ApplicationRecord
  belongs_to :client
  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :language, :active)
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:url, :point_of_sale_id)
    end
end

app/controllers/point_of_sales_controller.rb
class PointOfSalesController < ApplicationController
  before_action :set_point_of_sale, only: [:show, :edit, :update, :destroy]

  # GET /point_of_sales
  # GET /point_of_sales.json
  def index
    @point_of_sales = PointOfSale.all
  end

  # GET /point_of_sales/1
  # GET /point_of_sales/1.json
  def show
  end

  # GET /point_of_sales/new
  def new
    @point_of_sale = PointOfSale.new
  end

  # GET /point_of_sales/1/edit
  def edit
  end

  # POST /point_of_sales
  # POST /point_of_sales.json
  def create
    @point_of_sale = PointOfSale.new(point_of_sale_params)

    respond_to do |format|
      if @point_of_sale.save
        format.html { redirect_to @point_of_sale, notice: 'Point of sale was successfully created.' }
        format.json { render :show, status: :created, location: @point_of_sale }
      else
        format.html { render :new }
        format.json { render json: @point_of_sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /point_of_sales/1
  # PATCH/PUT /point_of_sales/1.json
  def update
    respond_to do |format|
      if @point_of_sale.update(point_of_sale_params)
        format.html { redirect_to @point_of_sale, notice: 'Point of sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @point_of_sale }
      else
        format.html { render :edit }
        format.json { render json: @point_of_sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /point_of_sales/1
  # DELETE /point_of_sales/1.json
  def destroy
    @point_of_sale.destroy
    respond_to do |format|
      format.html { redirect_to point_of_sales_url, notice: 'Point of sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_point_of_sale
      @point_of_sale = PointOfSale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def point_of_sale_params
      params.require(:point_of_sale).permit(:name, :city, :updated_at, :client_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/point_of_sales_helper.rb
module PointOfSalesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :language %>
    <%= form.text_field :language %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Language</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.language %></td>
        <td><%= client.active %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Language:</strong>
  <%= @client.language %>
</p>

<p>
  <strong>Active:</strong>
  <%= @client.active %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/images/_form.html.erb
<%= form_with(model: image, local: true) do |form| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :point_of_sale_id %>
    <%= form.text_field :point_of_sale_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Images</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Point of sale</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.url %></td>
        <td><%= image.point_of_sale %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @image.url %>
</p>

<p>
  <strong>Point of sale:</strong>
  <%= @image.point_of_sale %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/point_of_sales/_form.html.erb
<%= form_with(model: point_of_sale, local: true) do |form| %>
  <% if point_of_sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(point_of_sale.errors.count, "error") %> prohibited this point_of_sale from being saved:</h2>

      <ul>
      <% point_of_sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :updated_at %>
    <%= form.date_select :updated_at %>
  </div>

  <div class="field">
    <%= form.label :client_id %>
    <%= form.text_field :client_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/point_of_sales/edit.html.erb
<h1>Editing Point Of Sale</h1>

<%= render 'form', point_of_sale: @point_of_sale %>

<%= link_to 'Show', @point_of_sale %> |
<%= link_to 'Back', point_of_sales_path %>

app/views/point_of_sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Point Of Sales</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th>Updated at</th>
      <th>Client</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @point_of_sales.each do |point_of_sale| %>
      <tr>
        <td><%= point_of_sale.name %></td>
        <td><%= point_of_sale.city %></td>
        <td><%= point_of_sale.updated_at %></td>
        <td><%= point_of_sale.client %></td>
        <td><%= link_to 'Show', point_of_sale %></td>
        <td><%= link_to 'Edit', edit_point_of_sale_path(point_of_sale) %></td>
        <td><%= link_to 'Destroy', point_of_sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Point Of Sale', new_point_of_sale_path %>

app/views/point_of_sales/new.html.erb
<h1>New Point Of Sale</h1>

<%= render 'form', point_of_sale: @point_of_sale %>

<%= link_to 'Back', point_of_sales_path %>

app/views/point_of_sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @point_of_sale.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @point_of_sale.city %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @point_of_sale.updated_at %>
</p>

<p>
  <strong>Client:</strong>
  <%= @point_of_sale.client %>
</p>

<%= link_to 'Edit', edit_point_of_sale_path(@point_of_sale) %> |
<%= link_to 'Back', point_of_sales_path %>

app/views/welcome/index.html.erb
<p>You're on Rails!</p>